### PR TITLE
Fix undefined method config

### PR DESCRIPTION
**Pull request by benoittgt**
Hello 

This PR makes last version of factory_bot_rails working with Rails and other gems like `database_cleaner-active_record` when `ActiveRecord::Base` is loaded too early. Also the code is tested on last Rails version with the work of @y-yagi. I choose to cherry pick the commit because of great job.

I added a test that reproduce exactly the error and could behave as a non-regression test. Without the patch:

Screenshot 2023-11-23 at 12 45 29

Fix: #432
Fix: #436
Close: #429

For me the code of this gem is not bad, it's because of other gem that we have errors. See recommendations and discussions on this subject: https://github.com/rails/rails/issues/46567

cc @mike-burns

### CODE REVIEW

**Review by neilvcarvalho — APPROVED** [review]
LGTM! Thank you for cherry picking the fixes and adding a test. I'm asking for a second pair of eyes to take a look at this, then I'll cut a new release.

**Review by matsales28 — APPROVED** [review]
LGTM! I tested it locally, and it's working correctly. Ty for the fix!

**Comment by benoittgt** [comment]
Thanks a lot @neilvcarvalho and @matsales28. Do you plan to make a release? ✨

**Comment by neilvcarvalho** [comment]
@benoittgt Working on it right now, and should be up in a few minutes

**Comment by neilvcarvalho** [comment]
Released on https://github.com/thoughtbot/factory_bot_rails/releases/tag/v6.4.2 - thank you for working on this!

**Comment by benoittgt** [comment]
Thank you so much 🙌

**Pull request merged**
