### PR TITLE
Always execute a reload when Rails triggers one (instead of just on u…

### PR DESCRIPTION
**Pull request by jakeonfire**
…pdate) to prevent doubly-defined constants errors in factories when using Spring

- https://github.com/thoughtbot/factory_bot_rails/issues/323

### CODE REVIEW

**Comment by jakeonfire** [comment]
there are 3 failing specs where `FactoryBot.reload` gets called twice instead of once. i'm not sure why that is though.

**Comment by composerinteralia** [comment]
Maybe because the `to_prepare` hook gets invoke a variable number of times: https://github.com/rails/rails/issues/28108

**Comment by jakeonfire** [comment]
given this comment https://github.com/rails/rails/pull/28111#issuecomment-285370954 should the specs assert that `#reload` is called at least once?

**Comment by composerinteralia** [comment]
Yeah, that makes sense to me

**Comment by jakeonfire** [comment]
@composerinteralia if you feel like adding that spec to prove Spring and `#execute_if_updated` are incompatible, feel free!

**Comment by composerinteralia** [comment]
Thanks! I'll try to find some time on Friday to look at this.

**Comment by composerinteralia** [comment]
I added a failing test in https://github.com/thoughtbot/factory_bot_rails/pull/330

Can you give that a review when you have a chance? It looks like it does indeed pass with your PR. 🎉

**Comment by composerinteralia** [comment]
Thanks again!

**Pull request merged**
